MODULE fpe
     LOGICAL :: FPE_TRAP_INVALID
     LOGICAL :: FPE_TRAP_ZERO
     LOGICAL :: FPE_TRAP_OVERFLOW

CONTAINS
     SUBROUTINE SET_FPE
#ifdef __GFORTRAN__
          INTEGER(8) :: FLAGS = 0
          IF (FPE_TRAP_INVALID) FLAGS = FLAGS + 1
          IF (FPE_TRAP_ZERO) FLAGS = FLAGS + 4
          IF (FPE_TRAP_OVERFLOW) FLAGS = FLAGS + 8
          CALL GFORTRAN_SET_FPE(FLAGS)
#endif
     END SUBROUTINE SET_FPE
END MODULE fpe
