#!/bin/bash -e

RUN_NAME="FLD08"

MFIXSOLVER=./mfixsolver
if (($# > 0)); then
  MFIXSOLVER=$1
fi

rm -f POST_*.dat VTU*

rm -f ${RUN_NAME}*
${MFIXSOLVER} -f mfix.dat

post_dats=(AUTOTEST/POST*.dat)

for test_post_file in "${post_dats[@]}"; do
  numdiff -a 0.000001 -r 0.05 "${test_post_file}" \
    "$(basename "${test_post_file}")"
done
